codecov:
  token: 5ad93ecd-ffdc-4c92-b2db-a7c0ff1c1571

coverage:
  precision: 1
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        attachments: "sunburst, diff"

comment: off
