#!/usr/bin/env python
# -*- coding: utf-8 -*-

from optparse import OptionParser
import os
import sys

from txclib.commands import *
from txclib.utils import *
from txclib.project import *

reload(sys) # WTF? Otherwise setdefaultencoding doesn't work

# This block ensures that ^C interrupts are handled quietly.
try:
    import signal

    def exithandler(signum,frame):
        signal.signal(signal.SIGINT, signal.SIG_IGN)
        signal.signal(signal.SIGTERM, signal.SIG_IGN)
        sys.exit(1)

    signal.signal(signal.SIGINT, exithandler)
    signal.signal(signal.SIGTERM, exithandler)
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)

except KeyboardInterrupt:
    sys.exit(1)

# When we open file with f = codecs.open we specifi FROM what encoding to read
# This sets the encoding for the strings which are created with f.read()
sys.setdefaultencoding('utf-8')

VERSION="tx v0.1"

def main(argv):
    """
    Here we parse the flags (short, long) and we instantiate the classes.
    """
    usage = "usage: %prog [options] command [cmd_options]"

    parser = OptionParser(usage=usage, version=VERSION)
    parser.disable_interspersed_args()
    parser.add_option("-q", "--quiet", 
        action="store_true", dest="verbose", default=False,
        help="don't print status messages to stdout")
    parser.add_option("-r", "--root", action="store",
        dest="root_dir", type="string", default=os.getcwd(),
        help="change root directory (default is cwd)")
    parser.add_option("--traceback", action="store_true",
        dest="trace", default=False,
        help="print full traceback on exceptions")

    (options, args) = parser.parse_args()

    if len(args) < 1:
        parser.error("No command was given")

   
    cmd = args[0]
    try:
        exec_command(cmd, args[1:], options.root_dir)
    except KeyError:
        ERRMSG("Command %s not found" % cmd)
    except SystemExit:
        sys.exit()
    except:
        import traceback
        if options.trace:
            traceback.print_exc()
        else:
            formatted_lines = traceback.format_exc().splitlines()    
            ERRMSG(formatted_lines[-1])
        sys.exit(1)

# Run baby :) ... run
if __name__ == "__main__":
    # sys.argv[0] is the name of the script that we’re running.
    main(sys.argv[1:])
